### ISSUE TITLE
Проверка упражнений

### ISSUE THREAD

**Issue by kobzarius** [khabibullinra/unifloc_vba#19]
Проверить все упражнения, описания в коде и в интерфейсе и исправить чтобы все работало для выкладывания в ветку мастер

**Comment by kobzarius** [comment]
тут я постараюсь писать, над чем работаю, что сделал. Пока просто интерфейс оформляю, и меняю названия функций в ячейках на новые

**Comment by kobzarius** [comment]
разукрасил и поменял функции на новые в 6 первых упражнениях, можно проверить и забрать с dev2

**Comment by khabibullinra** [comment]
выложил упражнения в ветку мастер
